# Generated by Django 5.2.1 on 2025-05-18 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NCMXInconsistencies',
            fields=[
                ('num_nonconf', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, db_comment='Ответственное подразделение', max_length=10, null=True)),
                ('norm_doc', models.CharField(blank=True, db_comment='Нормативный документ', max_length=100, null=True)),
                ('nonconf', models.CharField(blank=True, db_comment='Описание несоответствия', max_length=1000, null=True)),
                ('report', models.CharField(blank=True, db_comment='Источник информации о несоответствии', max_length=100, null=True)),
                ('report_date', models.DateField(blank=True, db_comment='Дата утверждения источника', null=True)),
                ('analysis_start_date', models.DateField(blank=True, db_comment='Дата начала проведения анализа', null=True)),
                ('analysis_finish_date', models.DateField(blank=True, db_comment='Дата окончания проведения анализа', null=True)),
                ('head_auditor', models.CharField(blank=True, db_comment='Главный аудитор', max_length=50, null=True)),
                ('auditor', models.CharField(blank=True, db_comment='Аудитор', max_length=50, null=True)),
                ('reason', models.CharField(blank=True, db_comment='Причина несоответствия', max_length=100, null=True)),
                ('correction', models.CharField(blank=True, db_comment='Описание коррекции', max_length=1000, null=True)),
                ('correction_date', models.DateField(blank=True, db_comment='Дата внедрения коррекции', null=True)),
                ('resp_person_correction', models.CharField(blank=True, db_comment='Ответственное лицо', max_length=50, null=True)),
                ('corrective_action', models.CharField(blank=True, db_comment='Корректирующее действие', max_length=1000, null=True)),
                ('corrective_action_date', models.DateField(blank=True, db_comment='Дата внедрения кор. действия', null=True)),
                ('resp_person_corrective_action', models.CharField(blank=True, db_comment='Ответственное лицо', max_length=50, null=True)),
                ('estimate', models.IntegerField(blank=True, db_comment='Оценка', null=True)),
                ('nonconf_closure_date', models.DateField(blank=True, db_comment='Дата закрытия несоответствия', null=True)),
                ('resp_person_nonconf_closure', models.CharField(blank=True, db_comment='Ответственное лицо', max_length=50, null=True)),
                ('auto_data', models.DateTimeField(auto_now=True, db_comment='Дата изменения строки')),
            ],
            options={
                'db_table': 'NCMX_inconsistencies',
            },
        ),
        migrations.CreateModel(
            name='NCMXInconsistencyComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(db_comment='Автор комментария подтаблица\r\n', max_length=50)),
                ('comment_text', models.CharField(db_comment='Текс комментария подтаблица', max_length=1000)),
                ('auto_data', models.DateTimeField(auto_now_add=True, db_comment='Дата создания комментария')),
                ('num_nonconf', models.ForeignKey(db_comment='Номер несоответствия', on_delete=django.db.models.deletion.CASCADE, to='inconsistencies.ncmxinconsistencies')),
            ],
            options={
                'db_table': 'NCMX_inconsistency_comments',
            },
        ),
    ]
