# Generated by Django 5.2.1 on 2025-05-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconsistencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncmxinconsistencies',
            name='point',
            field=models.CharField(blank=True, db_comment='Номер пункта нормативного документа', max_length=50, null=True),
        ),
    ]
