# Generated by Django 5.2.1 on 2025-05-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inconsistencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NcmxInconsistency',
            new_name='NCMXInconsistencies',
        ),
        migrations.AlterModelTable(
            name='ncmxinconsistencies',
            table='NCMX_inconsistencies',
        ),
    ]
