# Generated by Django 5.2.1 on 2025-05-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconsistencies', '0002_rename_ncmxinconsistency_ncmxinconsistencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncmxinconsistencies',
            name='auto_data',
            field=models.DateTimeField(auto_now=True, db_comment='Дата изменения строки'),
        ),
        migrations.AlterField(
            model_name='ncmxinconsistencycomments',
            name='auto_data',
            field=models.DateTimeField(auto_now=True, db_comment='Дата создания комментария'),
        ),
    ]
