# Generated by Django 5.2.1 on 2025-05-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconsistencies', '0002_ncmxinconsistencies_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncmxinconsistencies',
            name='department',
        ),
        migrations.AddField(
            model_name='ncmxinconsistencies',
            name='department_correction',
            field=models.CharField(blank=True, db_comment='Подразделение для коррекции', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ncmxinconsistencies',
            name='department_corrective_action',
            field=models.CharField(blank=True, db_comment='Подразделение для корректирующего действия', max_length=10, null=True),
        ),
    ]
